// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1OQIyB_vz3X4gh9g3vqHWV4l5aGMhzpE',
    appId: '1:180049823735:web:933c5d2d9314342c9b10f2',
    messagingSenderId: '180049823735',
    projectId: 'darmanegeyahi',
    authDomain: 'darmanegeyahi.firebaseapp.com',
    storageBucket: 'darmanegeyahi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3yTUnhwFgejAG_nLBtGaJdzrsN0b5zoQ',
    appId: '1:180049823735:android:b40364ea22032c469b10f2',
    messagingSenderId: '180049823735',
    projectId: 'darmanegeyahi',
    storageBucket: 'darmanegeyahi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJS3RGHUv0D2XReP6_Pxgj2qdKtS6Tn6k',
    appId: '1:180049823735:ios:fd9b9128514dde8b9b10f2',
    messagingSenderId: '180049823735',
    projectId: 'darmanegeyahi',
    storageBucket: 'darmanegeyahi.firebasestorage.app',
    iosBundleId: 'com.example.darmajgarSabz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJS3RGHUv0D2XReP6_Pxgj2qdKtS6Tn6k',
    appId: '1:180049823735:ios:fd9b9128514dde8b9b10f2',
    messagingSenderId: '180049823735',
    projectId: 'darmanegeyahi',
    storageBucket: 'darmanegeyahi.firebasestorage.app',
    iosBundleId: 'com.example.darmajgarSabz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1OQIyB_vz3X4gh9g3vqHWV4l5aGMhzpE',
    appId: '1:180049823735:web:0c1326e0fb3f955a9b10f2',
    messagingSenderId: '180049823735',
    projectId: 'darmanegeyahi',
    authDomain: 'darmanegeyahi.firebaseapp.com',
    storageBucket: 'darmanegeyahi.firebasestorage.app',
  );
}
